### PR TITLE
Feature/new git version 2.10

### PR DESCRIPTION
**Pull request by akerl**
This is inclusive of my other open PR, due to the .json file (I figured unless there's a reason not to merge both, I'd avoid having the first merge cause a merge conflict in the 2nd)

If you want this one and need the other modded, I'm happy to fix up the PR to split them

### CODE REVIEW

**Comment by kristovatlas** [comment]
To keep things simple, I'd like to just match whichever version is latest for git (currently 2.10.2), although I didn't spot any security fixes in the git release notes since 2.9.3. https://github.com/git/git/tree/v2.10.1/Documentation/RelNotes

**Comment by akerl** [comment]
I think that ends up being a maintenance headache, since as a user that means that this repo needs an update every time git releases. For openssl, that makes sense, since the 1.0.2 track is only getting security fixes, but git releases pretty frequently for non-security changes

**Comment by kristovatlas** [comment]
Will plan to test and merge shortly. FYI, I'm also adding a script that will allow use of a `>=` operator when testing the version number of various programs.

**Comment by kristovatlas** [comment]
QA: Ran `python app.py --debug-print --report-only --skip-sudo-checks` and reviewed git-related output. Looks good.

**Pull request merged**
