### PR TITLE
osx-check.json typos in prompts: disaled >disabled

### PR DESCRIPTION
**Pull request by JimDennis**
Despite the warning regarding autogeneration of the osx-check.json
from its .hjson source; there are four instances of this typo in
the json which are not present in the *.hjson file.  Also the
hjson_to_json.py utility has an unsatisfied dependency on some
hjson module.

TODO: include references to the hjson module

### CODE REVIEW

**Comment by frenchi** [comment]
Was just about to open a PR with the same! 👍

**Comment by kristovatlas** [comment]
You are quite right about the typo, thanks for noticing. I do not understand this comment, can you clarify?

> Also the hjson_to_json.py utility has an unsatisfied dependency on some hjson module.

**Comment by JimDennis** [comment]
To understand the comment about **hjson_to_json.py** try to install and configure osx-config-check on a fresh system (with a factory installation of Python).  Then try to rebuild the .json file from the .hjson source (as indicated by the warning messages in that file/data structure).

**Comment by kristovatlas** [comment]
Ah, thanks for clarifying. That is entirely intentional -- I think the Hjson format is friendlier to developers who might want to contribute configurations to this project than pure JSON. Although I don't want users to have to install an HJSON module, I'm fine with developers having this requirement.

**Comment by JimDennis** [comment]
Anyone trying to contribute by modifying the HJSON file should have directions on how to test their changes before pushing their changes and creating a pull request.

That's how I encountered the issue.  I was unable test my changes in the expected fashion.

**Comment by JimDennis** [comment]
BTW: I'd prefer to use YAML as the "HJSON" format. :)

**Comment by kristovatlas** [comment]
Why YAML? I think more developers are familiar with JSON than YAML.

**Comment by kristovatlas** [comment]
#99 updates the JSON and obviates this PR. Thanks for the submission, though!

**Comment by kristovatlas** [comment]
@JimDennis it appears that there aren't any YAML Python modules that ship with OS X, so this would unfortunately break one of the design requirements for this project: https://github.com/kristovatlas/osx-config-check/wiki/Design-Principles

**Pull request closed without merging**
