### PR TITLE
Grep count fix

### PR DESCRIPTION
**Pull request by kiarafbickers**
Brackets added to remove the grep process from ps results. Value from /bin/sh` not showing on my machine, may want to change a pass value to '1' and the fail value to '2' or greater.

### CODE REVIEW

**Comment by kristovatlas** [comment]
Ooh, that's sneaky. Thanks, @kiaraRobles

**Comment by kristovatlas** [comment]
Are you able to resubmit this as a PR to the `develop` branch? I only merge to the `master` branch for releases.

**Comment by kristovatlas** [comment]
ping @kiaraRobles

**Comment by kiarafbickers** [comment]
On eet.

**Pull request closed without merging**
